# Generated by Django 4.2.5 on 2023-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('llmodel', models.CharField(max_length=150, null=True)),
                ('maxlength', models.IntegerField(null=True)),
                ('topk', models.IntegerField(null=True)),
                ('prompt_template', models.CharField(max_length=250, null=True)),
                ('reply', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, default='', max_length=600, null=True)),
            ],
        ),
    ]
